"""
enums.py — Controlled vocabularies.

AUTO-GENERATED by generate_pydantic.py from privacy_metamodel.ecore.
DO NOT EDIT THIS FILE MANUALLY.
To change an enum: edit generate_ecore.py → run generate_ecore.py
→ run generate_pydantic.py.

13 enums, one per EEnum in the metamodel.
Every enum here is the exclusive set of values the LLM extractor may
output for the corresponding metamodel attribute.
"""

from enum import Enum

class ActorRole(str, Enum):
    _Unset = "_Unset"
    DataSubject = "DataSubject"
    DataController = "DataController"
    DataProcessor = "DataProcessor"
    ThirdParty = "ThirdParty"

class ProcessingAction(str, Enum):
    _Unset = "_Unset"
    Collect = "Collect"
    Store = "Store"
    Use = "Use"
    Share = "Share"
    Transfer = "Transfer"
    Delete = "Delete"

class LegalBasisType(str, Enum):
    _Unset = "_Unset"
    Consent = "Consent"
    Contract = "Contract"
    LegalObligation = "LegalObligation"
    LegitimateInterest = "LegitimateInterest"
    VitalInterest = "VitalInterest"
    PublicTask = "PublicTask"

class PurposeCategory(str, Enum):
    _Unset = "_Unset"
    ServiceProvision = "ServiceProvision"
    Security = "Security"
    LegalCompliance = "LegalCompliance"
    Marketing = "Marketing"
    Analytics = "Analytics"
    Research = "Research"

class ConstraintType(str, Enum):
    _Unset = "_Unset"
    Temporal = "Temporal"
    Geographic = "Geographic"
    Usage = "Usage"
    Security = "Security"
    Retention = "Retention"
    PurposeLimitation = "PurposeLimitation"

class RightType(str, Enum):
    _Unset = "_Unset"
    Access = "Access"
    Rectification = "Rectification"
    Erasure = "Erasure"
    Restriction = "Restriction"
    Portability = "Portability"
    Objection = "Objection"
    AutomatedDecisionOptOut = "AutomatedDecisionOptOut"

class RetentionUnit(str, Enum):
    _Unset = "_Unset"
    Days = "Days"
    Months = "Months"
    Years = "Years"
    Indefinite = "Indefinite"

class RetentionTrigger(str, Enum):
    _Unset = "_Unset"
    CollectionDate = "CollectionDate"
    ContractEnd = "ContractEnd"
    LastActivity = "LastActivity"
    LegalObligationExpiry = "LegalObligationExpiry"
    ConsentWithdrawal = "ConsentWithdrawal"
    AccountDeletion = "AccountDeletion"

class WithdrawalChannel(str, Enum):
    _Unset = "_Unset"
    OnlineForm = "OnlineForm"
    Email = "Email"
    WrittenRequest = "WrittenRequest"
    InAppToggle = "InAppToggle"
    PhoneRequest = "PhoneRequest"
    InPerson = "InPerson"

class TransferMechanism(str, Enum):
    _Unset = "_Unset"
    AdequacyDecision = "AdequacyDecision"
    StandardContractualClauses = "StandardContractualClauses"
    BindingCorporateRules = "BindingCorporateRules"
    Consent = "Consent"
    ContractNecessity = "ContractNecessity"
    LegitimateInterest = "LegitimateInterest"
    Other = "Other"

class PersonalDataCategory(str, Enum):
    _Unset = "_Unset"
    Identifier = "Identifier"
    ContactInformation = "ContactInformation"
    LocationData = "LocationData"
    FinancialData = "FinancialData"
    HealthData = "HealthData"
    BiometricData = "BiometricData"
    BehavioralData = "BehavioralData"
    TechnicalData = "TechnicalData"
    ContentData = "ContentData"

class SensitivityLevel(str, Enum):
    _Unset = "_Unset"
    Low = "Low"
    Medium = "Medium"
    High = "High"
    SpecialCategory = "SpecialCategory"

class Identifiability(str, Enum):
    _Unset = "_Unset"
    Identified = "Identified"
    Pseudonymous = "Pseudonymous"
    Anonymous = "Anonymous"
