"""
models.py — Pydantic extraction schema.

AUTO-GENERATED by generate_pydantic.py from privacy_metamodel.ecore.
DO NOT EDIT THIS FILE MANUALLY.
To change a field: edit generate_ecore.py → run generate_ecore.py
→ run generate_pydantic.py.

Design rules (Ecore multiplicity → Python):
lower=1, upper=1   → required field, no default
lower=0, upper=1   → Optional[T] = None
lower=1, upper=-1  → List[T], min_length=1
lower=0, upper=-1  → List[T] = []
EString/ELong      → str / int
EEnum              → enum class from enums.py
EReference         → nested model class (containment)

ID fields (ending in 'Id') get a _new_id() default_factory so the
LLM can omit them safely.

source_clause is injected on every model for RAG traceability.
It has no counterpart in the Ecore metamodel.

OCL constraints are imported from _ocl_validators.py and attached
as @model_validator methods. Edit that file to change constraint logic.
"""

from __future__ import annotations

import uuid
import warnings
from typing import List, Optional

from pydantic import BaseModel, Field, field_validator, model_validator

from .enums import (
ActorRole,
ConstraintType,
Identifiability,
LegalBasisType,
PersonalDataCategory,
ProcessingAction,
PurposeCategory,
RetentionTrigger,
RetentionUnit,
RightType,
SensitivityLevel,
TransferMechanism,
WithdrawalChannel,
)

from ._ocl_validators import (
ocl_constraint_3_warning,
ocl_constraint_dt1,
ocl_constraint_2,
ocl_constraint_4_warning,
ocl_constraint_01,
)


# ── Utility ───────────────────────────────────────────────────────────────────

def _new_id(prefix: str) -> str:
    """Default ID factory — used when the LLM omits an ID field."""
    return f"{prefix}_{uuid.uuid4().hex[:8]}"


class _Base(BaseModel):
    """Common config for all schema models."""
    model_config = {"populate_by_name": True, "str_strip_whitespace": True}

class JurisdictionModel(_Base):
    """
    Metamodel class: Jurisdiction
    Auto-generated from privacy_metamodel.ecore.
    """
    jurisdiction_id: str = Field(default_factory=lambda: _new_id("jur"), alias="jurisdictionId")
    name: str
    description: Optional[str] = Field(default=None)
    source_clause: str = Field(default="", description="RAG chunk citation that justified this extraction, e.g. 'GDPR Art.6(1)(a)'.")


class RegulationModel(_Base):
    regulation_id: str = Field(
        default_factory=lambda: _new_id("reg"),
        alias="regulationId",
    )
    name: str = Field(
        description="Short name of the regulation, e.g. 'GDPR', 'CCPA', 'LGPD'."
    )
    version: str = Field(
        default="",
        description="Version or amendment identifier."
    )
    description: str = Field(
        default="",
        description="Brief description of the regulation's scope."
    )
    jurisdiction: List[JurisdictionModel] = Field(
        min_length=1,
        description="[OCL constraint_2] Every regulation must have at least one jurisdiction."
    )
    source_clause: str = Field(
        default="",
        description="RAG chunk citation for this regulation reference."
    )

    @field_validator("version", "description", "source_clause", mode="before")
    @classmethod
    def _coerce_none_to_empty(cls, v):
        """LLMs sometimes emit null for optional string fields. Coerce to ''."""
        return v if v is not None else ""


class ActorModel(_Base):
    """
    Metamodel class: Actor
    Auto-generated from privacy_metamodel.ecore.
    """
    actor_id: str = Field(default_factory=lambda: _new_id("act"), alias="actorId")
    name: str
    role: ActorRole
    source_clause: str = Field(default="", description="RAG chunk citation that justified this extraction, e.g. 'GDPR Art.6(1)(a)'.")


class PersonalDataModel(_Base):
    """
    Metamodel class: PersonalData
    Auto-generated from privacy_metamodel.ecore.
    """
    data_id: str = Field(default_factory=lambda: _new_id("dat"), alias="dataId")
    description: str
    source: str
    category: PersonalDataCategory
    sensitivity: SensitivityLevel
    identifiability: Identifiability
    source_clause: str = Field(default="", description="RAG chunk citation that justified this extraction, e.g. 'GDPR Art.6(1)(a)'.")
    
    
    @field_validator("category", mode="before")
    @classmethod
    def _coerce_category(cls, v):
        """Coerce unknown category values to General/Identifier default."""
        valid = {
            "Identifier", "ContactInformation", "LocationData",
            "FinancialData", "HealthData", "BiometricData",
            "BehavioralData", "TechnicalData", "ContentData"
        }
        return v if v in valid else "Identifier"


class ProcessingActivityModel(_Base):
    """
    Metamodel class: ProcessingActivity
    Auto-generated from privacy_metamodel.ecore.

    OCL validators attached from _ocl_validators.py:
    ocl_constraint_3_warning
    """
    activity_id: str = Field(default_factory=lambda: _new_id("prc"), alias="activityId")
    description: str
    action: ProcessingAction
    risk_assessment_reference: Optional[str] = Field(default=None, alias="riskAssessmentReference")
    data_processed: List[PersonalDataModel] = Field(alias="dataProcessed", min_length=1)
    source_clause: str = Field(default="", description="RAG chunk citation that justified this extraction, e.g. 'GDPR Art.6(1)(a)'.")

@model_validator(mode='after')
def _ocl_constraint_3_warning(self):
    return ocl_constraint_3_warning(self)



class DataTransferModel(_Base):
    """
    Metamodel: Processing.DataTransfer
    A cross-border data transfer — structurally distinct from ProcessingActivity
    so GDPR Ch.V, LGPD Art.33, and CCPA data-sale provisions each get their
    own typed extraction target.

    OCL constraint_dt1 (error):
        mechanism = AdequacyDecision implies adequacyDecisionRef must be set.
    """
    transfer_id: str = Field(
        default_factory=lambda: _new_id("xfr"),
        alias="transferId",
    )
    mechanism: TransferMechanism = Field(
        description="Legal instrument authorising the cross-border transfer."
    )
    adequacy_decision_ref: Optional[str] = Field(
        default=None,
        alias="adequacyDecisionRef",
        description=(
            "Reference to the adequacy decision document. "
            "Required when mechanism=AdequacyDecision."
        ),
    )
    destination_jurisdiction: List[JurisdictionModel] = Field(
        min_length=1,
        alias="destinationJurisdiction",
        description="Destination jurisdiction(s) for the transfer."
    )
    data_transferred: List[PersonalDataModel] = Field(
        min_length=1,
        alias="dataTransferred",
        description="Personal data categories being transferred."
    )
    source_clause: str = Field(
        default="",
        description="RAG chunk citation, e.g. 'GDPR Art.46(2)(c)'."
    )

    @field_validator("destination_jurisdiction", mode="before")
    @classmethod
    def _ensure_destination_jurisdiction(cls, v):
        """LLMs sometimes emit destinationJurisdiction: [] — inject unknown placeholder."""
        if not v:
            return [{"jurisdictionId": "UNKNOWN", "name": "Unknown", "source_clause": ""}]
        return v

    @field_validator("data_transferred", mode="before")
    @classmethod
    def _ensure_data_transferred(cls, v):
        """LLMs sometimes emit dataTransferred: [] — inject generic personal data placeholder."""
        if not v:
            return [{
                "dataId":          "",
                "description":     "personal data",
                "source":          "stated",
                "category":        "General",
                "sensitivity":     "Low",
                "identifiability": "Identified",
                "source_clause":   ""
            }]
        return v

    @model_validator(mode="after")
    def ocl_constraint_dt1(self) -> "DataTransferModel":
        """
        OCL constraint_dt1 (error):
        AdequacyDecision mechanism requires adequacyDecisionRef.
        """
        if (
            self.mechanism == TransferMechanism.AdequacyDecision
            and not self.adequacy_decision_ref
        ):
            raise ValueError(
                f"[constraint_dt1 / error] DataTransfer '{self.transfer_id}': "
                f"mechanism=AdequacyDecision but adequacyDecisionRef is empty. "
                f"Cite the EC adequacy decision document "
                f"(e.g. 'EC Decision 2019/419 for Japan')."
            )
        return self



class PurposeModel(_Base):
    """
    Metamodel class: Purpose
    Auto-generated from privacy_metamodel.ecore.
    """
    purpose_id: str = Field(default_factory=lambda: _new_id("pur"), alias="purposeId")
    description: str
    category: PurposeCategory
    source_clause: str = Field(default="", description="RAG chunk citation that justified this extraction, e.g. 'GDPR Art.6(1)(a)'.")


class LegalBasisModel(_Base):
    """
    Metamodel class: LegalBasis
    Auto-generated from privacy_metamodel.ecore.
    """
    basis_id: str = Field(default_factory=lambda: _new_id("lb"), alias="basisId")
    type: LegalBasisType
    evidence: str
    jurisdiction: List[JurisdictionModel] = Field(min_length=1)
    source_clause: str = Field(default="", description="RAG chunk citation that justified this extraction, e.g. 'GDPR Art.6(1)(a)'.")


    @field_validator("jurisdiction", mode="before")
    @classmethod
    def _ensure_jurisdiction(cls, v):
        """Coerce empty jurisdiction list to a generic unknown placeholder.
        The assembler prompt provides law-specific jurisdiction via
        _synthesise_regulation_json — this is only a structural safety net.
        """
        if not v:
            return [{
                "jurisdictionId": "UNKNOWN",
                "name":           "Unknown",
                "source_clause":  ""
            }]
        return v

class ConstraintModel(_Base):
    """
    Metamodel class: Constraint
    Auto-generated from privacy_metamodel.ecore.
    """
    constraint_id: str = Field(default_factory=lambda: _new_id("con"), alias="constraintId")
    type: ConstraintType
    expression: str
    enforcement_level: str = Field(alias="enforcementLevel")
    source_clause: str = Field(default="", description="RAG chunk citation that justified this extraction, e.g. 'GDPR Art.6(1)(a)'.")


class RightModel(_Base):
    """
    Metamodel class: Right
    Auto-generated from privacy_metamodel.ecore.
    """
    right_id: str = Field(default_factory=lambda: _new_id("rig"), alias="rightId")
    type: RightType
    trigger_condition: str = Field(alias="triggerCondition")
    fulfillment_process: str = Field(alias="fulfillmentProcess")
    source_clause: str = Field(default="", description="RAG chunk citation that justified this extraction, e.g. 'GDPR Art.6(1)(a)'.")


class RetentionPolicyModel(_Base):
    """
    Metamodel class: RetentionPolicy
    Auto-generated from privacy_metamodel.ecore.
    """
    retention_id: str = Field(default_factory=lambda: _new_id("ret"), alias="retentionId")
    duration: int
    unit: RetentionUnit
    trigger: RetentionTrigger
    basis_article: Optional[str] = Field(default=None, alias="basisArticle")
    source_clause: str = Field(default="", description="RAG chunk citation that justified this extraction, e.g. 'GDPR Art.6(1)(a)'.")


class ConsentWithdrawalModel(_Base):
    """
    Metamodel class: ConsentWithdrawal
    Auto-generated from privacy_metamodel.ecore.
    """
    withdrawal_id: str = Field(default_factory=lambda: _new_id("cwd"), alias="withdrawalId")
    channel: List[WithdrawalChannel] = Field(min_length=1)
    deadline: str
    effect_on_prior_processing: str = Field(alias="effectOnPriorProcessing")
    source_clause: str = Field(default="", description="RAG chunk citation that justified this extraction, e.g. 'GDPR Art.6(1)(a)'.")


class PolicyStatementModel(_Base):
    """
    Metamodel class: PolicyStatement
    Auto-generated from privacy_metamodel.ecore.

    OCL validators attached from _ocl_validators.py:
    ocl_constraint_2
    ocl_constraint_4_warning
    """
    statement_id: str = Field(default_factory=lambda: _new_id("stmt"), alias="statementId")
    description: str
    actor: ActorModel
    purposes: List[PurposeModel] = Field(min_length=1)
    processing_activity: ProcessingActivityModel = Field(alias="processingActivity")
    legal_basis: LegalBasisModel = Field(alias="legalBasis")
    governing_regulations: List[RegulationModel] = Field(alias="governingRegulations", min_length=1)
    constraints: List[ConstraintModel] = Field(min_length=1)
    right_impacted: List[RightModel] = Field(alias="rightImpacted", min_length=1)
    retention_policies: List[RetentionPolicyModel] = Field(default=[], alias="retentionPolicies")
    data_transfers: List[DataTransferModel] = Field(default=[], alias="dataTransfers")
    consent_withdrawal: List[ConsentWithdrawalModel] = Field(default=[], alias="consentWithdrawal")
    source_clause: str = Field(default="", description="RAG chunk citation that justified this extraction, e.g. 'GDPR Art.6(1)(a)'.")

@model_validator(mode='after')
def _ocl_constraint_2(self):
    return ocl_constraint_2(self)

@model_validator(mode='after')
def _ocl_constraint_4_warning(self):
    return ocl_constraint_4_warning(self)



class PrivacyPolicyModel(_Base):
    """
    Metamodel class: PrivacyPolicy
    Auto-generated from privacy_metamodel.ecore.

    OCL validators attached from _ocl_validators.py:
    ocl_constraint_01
    """
    policy_id: str = Field(default_factory=lambda: _new_id("pol"), alias="policyId")
    version: str
    valid_from: int = Field(alias="validFrom")
    valid_to: int = Field(alias="validTo")
    statements: List[PolicyStatementModel] = Field(min_length=1)
    source_clause: str = Field(default="", description="RAG chunk citation that justified this extraction, e.g. 'GDPR Art.6(1)(a)'.")

@model_validator(mode='after')
def _ocl_constraint_01(self):
    return ocl_constraint_01(self)

