        """
        models.py — Pydantic extraction schema.

        AUTO-GENERATED by generate_pydantic.py from privacy_metamodel.ecore.
        DO NOT EDIT THIS FILE MANUALLY.
        To change a field: edit generate_ecore.py → run generate_ecore.py
        → run generate_pydantic.py.

        Design rules (Ecore multiplicity → Python):
          lower=1, upper=1   → required field, no default
          lower=0, upper=1   → Optional[T] = None
          lower=1, upper=-1  → List[T], min_length=1
          lower=0, upper=-1  → List[T] = []
          EString/ELong      → str / int
          EEnum              → enum class from enums.py
          EReference         → nested model class (containment)

        ID fields (ending in 'Id') get a _new_id() default_factory so the
        LLM can omit them safely.

        source_clause is injected on every model for RAG traceability.
        It has no counterpart in the Ecore metamodel.

        OCL constraints are imported from _ocl_validators.py and attached
        as @model_validator methods. Edit that file to change constraint logic.
        """

        from __future__ import annotations

        import uuid
        import warnings
        from typing import List, Optional

        from pydantic import BaseModel, Field, model_validator

        from .enums import (
    ActorRole,
    ConstraintType,
    EnforcementLevel,
    Identifiability,
    LegalBasisType,
    PersonalDataCategory,
    ProcessingAction,
    PurposeCategory,
    RetentionTrigger,
    RetentionUnit,
    RightType,
    SensitivityLevel,
    TransferMechanism,
    WithdrawalChannel,
)

        from ._ocl_validators import (
    ocl_constraint_3_warning,
    ocl_constraint_dt1,
    ocl_constraint_2,
    ocl_constraint_4_warning,
    ocl_constraint_01,
)


        # ── Utility ───────────────────────────────────────────────────────────────────

        def _new_id(prefix: str) -> str:
            """Default ID factory — used when the LLM omits an ID field."""
            return f"{prefix}_{uuid.uuid4().hex[:8]}"


        class _Base(BaseModel):
            """Common config for all schema models."""
            model_config = {"populate_by_name": True, "str_strip_whitespace": True}

class JurisdictionModel(_Base):
    """
    Metamodel class: Jurisdiction
    Auto-generated from privacy_metamodel.ecore.
    """
    jurisdiction_id: str = Field(default_factory=lambda: _new_id("jur"), alias="jurisdictionId")
    name: str
    description: Optional[str] = Field(default=None)
    source_clause: str = Field(default="", description="RAG chunk citation that justified this extraction, e.g. 'GDPR Art.6(1)(a)'.")


class RegulationModel(_Base):
    """
    Metamodel class: Regulation
    Auto-generated from privacy_metamodel.ecore.
    """
    regulation_id: str = Field(default_factory=lambda: _new_id("reg"), alias="regulationId")
    name: str
    version: Optional[str] = Field(default=None)
    description: Optional[str] = Field(default=None)
    jurisdiction: List[JurisdictionModel] = Field(default=[])
    source_clause: str = Field(default="", description="RAG chunk citation that justified this extraction, e.g. 'GDPR Art.6(1)(a)'.")


class ActorModel(_Base):
    """
    Metamodel class: Actor
    Auto-generated from privacy_metamodel.ecore.
    """
    actor_id: str = Field(default_factory=lambda: _new_id("act"), alias="actorId")
    name: str
    role: ActorRole
    source_clause: str = Field(default="", description="RAG chunk citation that justified this extraction, e.g. 'GDPR Art.6(1)(a)'.")


class PersonalDataModel(_Base):
    """
    Metamodel class: PersonalData
    Auto-generated from privacy_metamodel.ecore.
    """
    data_id: str = Field(default_factory=lambda: _new_id("dat"), alias="dataId")
    description: str
    source: Optional[str] = Field(default=None)
    category: PersonalDataCategory
    sensitivity: SensitivityLevel
    identifiability: Identifiability
    source_clause: str = Field(default="", description="RAG chunk citation that justified this extraction, e.g. 'GDPR Art.6(1)(a)'.")


class ProcessingActivityModel(_Base):
    """
    Metamodel class: ProcessingActivity
    Auto-generated from privacy_metamodel.ecore.

    OCL validators attached from _ocl_validators.py:
      ocl_constraint_3_warning
    """
    activity_id: str = Field(default_factory=lambda: _new_id("prc"), alias="activityId")
    description: str
    action: ProcessingAction
    risk_assessment_reference: Optional[str] = Field(default=None, alias="riskAssessmentReference")
    data_processed: List[PersonalDataModel] = Field(default=[], alias="dataProcessed")
    source_clause: str = Field(default="", description="RAG chunk citation that justified this extraction, e.g. 'GDPR Art.6(1)(a)'.")

    @model_validator(mode='after')
    def _ocl_constraint_3_warning(self):
        return ocl_constraint_3_warning(self)



class DataTransferModel(_Base):
    """
    Metamodel class: DataTransfer
    Auto-generated from privacy_metamodel.ecore.

    OCL validators attached from _ocl_validators.py:
      ocl_constraint_dt1
    """
    transfer_id: str = Field(default_factory=lambda: _new_id("xfr"), alias="transferId")
    mechanism: TransferMechanism
    adequacy_decision_ref: Optional[str] = Field(default=None, alias="adequacyDecisionRef")
    destination_jurisdiction: List[JurisdictionModel] = Field(default=[], alias="destinationJurisdiction")
    data_transferred: List[PersonalDataModel] = Field(default=[], alias="dataTransferred")
    source_clause: str = Field(default="", description="RAG chunk citation that justified this extraction, e.g. 'GDPR Art.6(1)(a)'.")

    @model_validator(mode='after')
    def _ocl_constraint_dt1(self):
        return ocl_constraint_dt1(self)



class PurposeModel(_Base):
    """
    Metamodel class: Purpose
    Auto-generated from privacy_metamodel.ecore.
    """
    purpose_id: str = Field(default_factory=lambda: _new_id("pur"), alias="purposeId")
    description: str
    category: PurposeCategory
    source_clause: str = Field(default="", description="RAG chunk citation that justified this extraction, e.g. 'GDPR Art.6(1)(a)'.")


class LegalBasisModel(_Base):
    """
    Metamodel class: LegalBasis
    Auto-generated from privacy_metamodel.ecore.
    """
    basis_id: str = Field(default_factory=lambda: _new_id("lb"), alias="basisId")
    type: LegalBasisType
    evidence: Optional[str] = Field(default=None)
    jurisdiction: List[JurisdictionModel] = Field(default=[])
    source_clause: str = Field(default="", description="RAG chunk citation that justified this extraction, e.g. 'GDPR Art.6(1)(a)'.")


class ConstraintModel(_Base):
    """
    Metamodel class: Constraint
    Auto-generated from privacy_metamodel.ecore.
    """
    constraint_id: str = Field(default_factory=lambda: _new_id("con"), alias="constraintId")
    type: ConstraintType
    expression: str
    enforcement_level: EnforcementLevel = Field(alias="enforcementLevel")
    source_clause: str = Field(default="", description="RAG chunk citation that justified this extraction, e.g. 'GDPR Art.6(1)(a)'.")


class RightModel(_Base):
    """
    Metamodel class: Right
    Auto-generated from privacy_metamodel.ecore.
    """
    right_id: str = Field(default_factory=lambda: _new_id("rig"), alias="rightId")
    type: RightType
    trigger_condition: Optional[str] = Field(default=None, alias="triggerCondition")
    fulfillment_process: Optional[str] = Field(default=None, alias="fulfillmentProcess")
    source_clause: str = Field(default="", description="RAG chunk citation that justified this extraction, e.g. 'GDPR Art.6(1)(a)'.")


class RetentionPolicyModel(_Base):
    """
    Metamodel class: RetentionPolicy
    Auto-generated from privacy_metamodel.ecore.
    """
    retention_id: str = Field(default_factory=lambda: _new_id("ret"), alias="retentionId")
    duration: Optional[int] = Field(default=None)
    unit: RetentionUnit
    trigger: RetentionTrigger
    basis_article: Optional[str] = Field(default=None, alias="basisArticle")
    source_clause: str = Field(default="", description="RAG chunk citation that justified this extraction, e.g. 'GDPR Art.6(1)(a)'.")


class ConsentWithdrawalModel(_Base):
    """
    Metamodel class: ConsentWithdrawal
    Auto-generated from privacy_metamodel.ecore.
    """
    withdrawal_id: str = Field(default_factory=lambda: _new_id("cwd"), alias="withdrawalId")
    channel: List[WithdrawalChannel] = Field(default=[])
    deadline: Optional[str] = Field(default=None)
    effect_on_prior_processing: Optional[str] = Field(default=None, alias="effectOnPriorProcessing")
    source_clause: str = Field(default="", description="RAG chunk citation that justified this extraction, e.g. 'GDPR Art.6(1)(a)'.")


class PolicyStatementModel(_Base):
    """
    Metamodel class: PolicyStatement
    Auto-generated from privacy_metamodel.ecore.

    OCL validators attached from _ocl_validators.py:
      ocl_constraint_2
      ocl_constraint_4_warning
    """
    statement_id: str = Field(default_factory=lambda: _new_id("stmt"), alias="statementId")
    description: str
    source_article: Optional[str] = Field(default=None, alias="sourceArticle")
    source_text: Optional[str] = Field(default=None, alias="sourceText")
    source_offset_start: Optional[int] = Field(default=None, alias="sourceOffsetStart")
    source_offset_end: Optional[int] = Field(default=None, alias="sourceOffsetEnd")
    actor: Optional[ActorModel] = Field(default=None)
    purposes: List[PurposeModel] = Field(default=[])
    processing_activity: Optional[ProcessingActivityModel] = Field(default=None, alias="processingActivity")
    legal_basis: Optional[LegalBasisModel] = Field(default=None, alias="legalBasis")
    governing_regulations: List[RegulationModel] = Field(default=[], alias="governingRegulations")
    constraints: List[ConstraintModel] = Field(default=[])
    rights_impacted: List[RightModel] = Field(default=[], alias="rightsImpacted")
    retention_policies: List[RetentionPolicyModel] = Field(default=[], alias="retentionPolicies")
    data_transfers: List[DataTransferModel] = Field(default=[], alias="dataTransfers")
    consent_withdrawal: List[ConsentWithdrawalModel] = Field(default=[], alias="consentWithdrawal")
    source_clause: str = Field(default="", description="RAG chunk citation that justified this extraction, e.g. 'GDPR Art.6(1)(a)'.")

    @model_validator(mode='after')
    def _ocl_constraint_2(self):
        return ocl_constraint_2(self)

    @model_validator(mode='after')
    def _ocl_constraint_4_warning(self):
        return ocl_constraint_4_warning(self)



class PrivacyPolicyModel(_Base):
    """
    Metamodel class: PrivacyPolicy
    Auto-generated from privacy_metamodel.ecore.

    OCL validators attached from _ocl_validators.py:
      ocl_constraint_01
    """
    policy_id: str = Field(default_factory=lambda: _new_id("pol"), alias="policyId")
    version: str
    valid_from: Optional[int] = Field(default=None, alias="validFrom")
    valid_to: Optional[int] = Field(default=None, alias="validTo")
    statements: List[PolicyStatementModel] = Field(min_length=1)
    actor_catalogue: List[ActorModel] = Field(default=[], alias="actorCatalogue")
    data_catalogue: List[PersonalDataModel] = Field(default=[], alias="dataCatalogue")
    regulation_catalogue: List[RegulationModel] = Field(default=[], alias="regulationCatalogue")
    jurisdiction_catalogue: List[JurisdictionModel] = Field(default=[], alias="jurisdictionCatalogue")
    source_clause: str = Field(default="", description="RAG chunk citation that justified this extraction, e.g. 'GDPR Art.6(1)(a)'.")

    @model_validator(mode='after')
    def _ocl_constraint_01(self):
        return ocl_constraint_01(self)

